# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [4]:
import numpy as np
height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

bmi = weight / (height**2) * 730

for h, w, b in zip(height, weight, bmi):
    print(f"Height: {h} inches, Weight: {w} lbs, BMI: {b:.2f}")


Height: 69 inches, Weight: 110 lbs, BMI: 16.87
Height: 70 inches, Weight: 120 lbs, BMI: 17.88
Height: 71 inches, Weight: 130 lbs, BMI: 18.83
Height: 72 inches, Weight: 140 lbs, BMI: 19.71
Height: 73 inches, Weight: 150 lbs, BMI: 20.55
Height: 74 inches, Weight: 160 lbs, BMI: 21.33
Height: 75 inches, Weight: 170 lbs, BMI: 22.06


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [8]:
import numpy as np

def create_random_matrix(rows, columns, shape="square", dtype=float):
    
    if shape == "square":
        matrix = np.random.random((rows, columns))
    elif shape == "triangle":
        size = max(rows, columns)
        matrix = np.random.random((size, size))
        matrix = matrix[:rows, :columns]
   
    return matrix.astype(dtype)

rows = 3
columns = 4
random_matrix = create_random_matrix(rows, columns)
print("Square Matrix:")
print(random_matrix)

square_matrix = create_random_matrix(rows, rows, shape="square", dtype=int)
print("\ntriangle Matrix:")
print(square_matrix)


Square Matrix:
[[0.88344324 0.84440308 0.61485259 0.94971405]
 [0.61071255 0.70064657 0.61754614 0.99677398]
 [0.52301142 0.16078329 0.53041981 0.51945636]]

triangle Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [12]:
import pandas as pd
import numpy as np
file_2017 = 'Boston Red Sox hitting data 2017.csv'
file_2018 = 'Boston Red Sox hitting data 2018.csv'

data_2017 = pd.read_csv(file_2017)
data_2018 = pd.read_csv(file_2018)

slg_2017 = data_2017['SLG']
slg_2018 = data_2018['SLG']

slg_array_2017 = np.array(slg_2017)
slg_array_2018 = np.array(slg_2018)

mean_slg_2017 = np.mean(slg_array_2017)
mean_slg_2018 = np.mean(slg_array_2018)

print(f"SLG in 2017: {mean_slg_2017}")
print(f"SLG in 2018: {mean_slg_2018}")

if mean_slg_2018 > mean_slg_2017:
    print("2018 was a better year based on SLG.")
elif mean_slg_2018 < mean_slg_2017:
    print("2017 was a better year based on SLG.")
else:
    print("Both years have the same SLG.")



SLG in 2017: 0.39334782608695656
SLG in 2018: 0.38750000000000007
2017 was a better year based on SLG.
